export enum UserErrorEnum {
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  USER_EMAIL_VERIFIED = 'USER_EMAIL_VERIFIED',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
  TOKEN_NOT_VALID_UUID = 'TOKEN_NOT_VALID_UUID',
  INVALID_EMAIL = 'INVALID_EMAIL'
}

export enum NotFoundErrorEnum {
  USER = 'USER_NOT_FOUND',
  VERIFY_TOKEN = 'VERIFY_TOKEN_NOT_FOUND',
  SESSION = 'SESSION_NOT_FOUND',
  RESET_TOKEN = 'RESET_TOKEN_NOT_FOUND'
}

export enum ForbiddenErrorEnum {
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN'
}

export enum FetalErrorEnum {
  TRANSPORTER_NOT_INITIALIZED = 'TRANSPORTER_NOT_INITIALIZED'
}
